Update notifylist.html.markdown
ns1-terraform/terraform-provider-ns1 pull request #156
Opened 2021-04-15 01:24 UTC by ionigman

Update to documentation to reflect proper usage for notify lists with monitoring.

2021-04-22 20:13 UTC, mburtless requested changes

2021-04-22 20:13 UTC, mburtless commented on website/docs/r/notifylist.html.markdown
> +}
extra `}`?

2021-04-22 20:17 UTC, mburtless requested changes

2021-04-22 20:17 UTC, mburtless commented on website/docs/r/notifylist.html.markdown
> +
extra `}` and whitespace?

2021-06-09 18:15 UTC, ionigman commented on website/docs/r/notifylist.html.markdown
> +
fixed

2021-06-10 15:21 UTC, mburtless requested changes

2021-06-10 15:21 UTC, mburtless commented on website/docs/r/notifylist.html.markdown
> + notifications {
Looks like indentation is off?  This doesn't appear to line up with the block above it.

2021-10-01 17:36 UTC, pcatalini commented
@ionigman any updates in this pr? otherwise, I think we can close it.

2026-08-06 16:35 UTC, closed without merging