DAITDS-142 Application support
ns1-terraform/terraform-provider-ns1 pull request #172
Opened 2021-08-27 21:02 UTC by pcatalini

2021-08-31 19:08 UTC, Zach-Johnson requested changes
Looks good, just a few minor things noted

2021-08-31 19:08 UTC, Zach-Johnson commented on ns1/resource_application.go
> +// ApplicationCreate creates the given zone in ns1
The comment on this is incorrect I think

2021-08-31 19:08 UTC, Zach-Johnson commented on ns1/resource_application.go
> +// ApplicationRead reads the given zone data from ns1
Comment looks wrong

2021-08-31 19:08 UTC, Zach-Johnson commented on ns1/resource_application.go
> +		if err == ns1.ErrApplicationMissing {
``` suggestion
		if errors.Is(err, ns1.ErrApplicationMissing) {
```

2021-08-31 19:08 UTC, Zach-Johnson commented on ns1/resource_application.go
> +// ApplicationDelete deletes the given zone from ns1
fix comment

2021-08-31 19:08 UTC, Zach-Johnson commented on ns1/resource_application.go
> +// ApplicationUpdate updates the zone with given params in ns1
fix comment

2021-08-31 19:08 UTC, Zach-Johnson commented on ns1/resource_application_test.go
> +			return fmt.Errorf("zone: got: %v want: %v", app.JobsPerTransaction, expected)
don't think this should say zone, various other spots with this as well

2021-08-31 19:08 UTC, Zach-Johnson commented on website/docs/r/application.html.markdown
> +# ns1\_application
is this supposed to have the `\` in it?

2021-08-31 19:51 UTC, mvkushnir commented on website/docs/r/application.html.markdown
> +* `hostmaster` - (Computed) The SOA Hostmaster.
What are these?

2021-08-31 21:23 UTC, pcatalini commented on website/docs/r/application.html.markdown
> +* `hostmaster` - (Computed) The SOA Hostmaster.
i forget to remove, thanks good catch

2021-09-01 17:53 UTC, mvkushnir approved these changes
Looks good, just one final change

2021-09-01 17:53 UTC, mvkushnir commented on website/docs/r/application.html.markdown
> +* `static_values` - (Computed) - Indicates whether or not to skip aggregation for this job's measurements
These should be optional, not computed (as they are up above)

2021-09-07 20:10 UTC, Zach-Johnson approved these changes
lgtm!

2021-09-07 20:11 UTC, merged