DAITDS-143 - Pulsar Job support to Terraform
ns1-terraform/terraform-provider-ns1 pull request #173
Opened 2021-08-27 21:50 UTC by ThiagoYU

2021-08-31 19:16 UTC, Zach-Johnson requested changes
looking good, just noted a few small things

2021-08-31 19:16 UTC, Zach-Johnson commented on ns1/resource_pulsar_job.go
> +		"typeid": {
I think `type_id` would be easier to read

2021-08-31 19:16 UTC, Zach-Johnson commented on ns1/resource_pulsar_job.go
> +		"jobid": {
same thing, consider making this `job_id`

2021-08-31 19:16 UTC, Zach-Johnson commented on ns1/resource_pulsar_job.go
> +		"appid": {
consider making this `app_id`

2021-08-31 19:16 UTC, Zach-Johnson commented on ns1/resource_pulsar_job.go
> +		if err == ns1.ErrAppMissing {
consider using `errors.Is(err, ns1.ErrAppMissing)` instead

2021-08-31 19:16 UTC, Zach-Johnson commented on ns1/resource_pulsar_job.go
> +		if err == ns1.ErrJobMissing {
consider using `errors.Is(err, ns1.ErrJobMissing)` instead

2021-08-31 19:52 UTC, mvkushnir commented on ns1/resource_pulsar_job.go
> +			Default:  true,
I think this should be default false

2021-08-31 19:54 UTC, mvkushnir commented on ns1/resource_pulsar_job.go
> +			Optional: true,
this should be required

2021-09-01 17:55 UTC, mvkushnir approved these changes
👍 Looks good! Just one final comment

2021-09-01 17:55 UTC, mvkushnir commented on website/docs/r/pulsar_job.html .markdown
> +* `satuc_values` - (Optional) Indicates wheter or not to skip aggregation for this job's measurements.
Typo? should be `static_values`

2021-09-07 20:07 UTC, Zach-Johnson approved these changes
lgtm!

2021-09-07 20:10 UTC, merged